### ISSUE TITLE
Streaming video outside the network

### ISSUE THREAD

**Issue by jcmorales85** [Instagit/videojs-sublime#6]
This plugin works amazing but I can only get it to work internally.

I've followed:

https://doc.owncloud.org/server/8.0/admin_manual/configuration_files/serving_static_files_configuration.html

and set up the following:
  SetEnv MOD_X_SENDFILE_ENABLED 1
  XSendFile On
  XSendFilePath /home/valerio

but I can only get the videos to play on my internal network (192.X.X.X), I can't get the videos to play from an external network.

**Comment by Instagit** [comment]
What happens when you try to play the videos from an external network? I never had problems with that and you're the first to report this.

I'll look into it but honestly, the video streaming in ownCloud seems to be a bit of a mess right now. The things that work for one user don't work with another setup and the other way around. I might need help from someone who knows more about ownCloud than I do.

On another note: You said in the comments on the plugin page: "I can play videos from a shared (local) folder without any problems." Is that with the latest ownCloud version (8.2.0)? Because that never worked for me and other users are reporting the same.

**Comment by jcmorales85** [comment]
No, no issues when I try to play outside the network.  The video just keeps loading and nothing ever happens.  When I'm on the internal network (192.168.X.X), the plug in works flawlessly and beautifully.

I'm in the process of doing a fresh install of 8.2.  I'll get back to you with results.

**Comment by jcmorales85** [comment]
As good as this app is, it looks like it may become obsolete in regards to Owncloud.

XSendfile support was removed in 8.2
https://github.com/owncloud/core/issues/18870

It's a shame.  I'm a big fan of the app and out of all the solutions offered (including the built in video player), it was the one that provided the smoothest playback.

**Comment by Instagit** [comment]
XSendfile is only needed for Safari, so it's not a big loss.

**Comment by Instagit** [comment]
Could you try again with the latest version? I changed the link for accessing the videos, that solved a lot of playback problems with Chrome and shared folders.

**Comment by Instagit** [comment]
I'll close this for now due to inactivity. Feel free to reopen if there's still a problem.
